//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coming_goods
    {
        public decimal C__партии { get; set; }
        public string Наименование { get; set; }
        public decimal Тип { get; set; }
        public decimal Кол_во { get; set; }
        public Nullable<System.DateTime> Прибытие { get; set; }
    }
}
