//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.Send = new HashSet<Send>();
            this.Users_inv = new HashSet<Users_inv>();
        }
    
        public decimal id_invoice { get; set; }
        public System.DateTime data_get { get; set; }
        public decimal id_contractor { get; set; }
        public decimal summ { get; set; }
        public bool paid { get; set; }
        public Nullable<System.DateTime> data_paid { get; set; }
        public bool good_issue { get; set; }
        public Nullable<System.DateTime> data_issue { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual ICollection<Send> Send { get; set; }
        public virtual ICollection<Users_inv> Users_inv { get; set; }
    }
}
