//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_goods
    {
        public decimal id_invoice { get; set; }
        public string brand { get; set; }
        public decimal count { get; set; }
        public decimal price { get; set; }
        public decimal cost { get; set; }
        public decimal margin { get; set; }
    }
}
