//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchandise
    {
        public Merchandise()
        {
            this.Send = new HashSet<Send>();
        }
    
        public decimal id_merch { get; set; }
        public string brand { get; set; }
        public string specif_n { get; set; }
        public decimal id_type { get; set; }
        public decimal count_order { get; set; }
        public decimal count_stored { get; set; }
        public decimal count_send { get; set; }
        public decimal count_booked { get; set; }
        public decimal consignment { get; set; }
        public decimal margin { get; set; }
        public decimal cost { get; set; }
        public bool arrived { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Types Types { get; set; }
        public virtual ICollection<Send> Send { get; set; }
    }
}
