//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Merchandise = new HashSet<Merchandise>();
        }
    
        public decimal consigment { get; set; }
        public decimal id_contractor { get; set; }
        public Nullable<decimal> summ { get; set; }
        public Nullable<System.DateTime> date_order { get; set; }
        public Nullable<System.DateTime> date_import { get; set; }
        public decimal id_user { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual ICollection<Merchandise> Merchandise { get; set; }
        public virtual Users Users { get; set; }
    }
}
