//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_to_sell
    {
        public decimal id_merch { get; set; }
        public string Наименование { get; set; }
        public string name { get; set; }
        public decimal C__партии { get; set; }
        public Nullable<decimal> Кол_во { get; set; }
        public Nullable<decimal> Цена { get; set; }
    }
}
