//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Search_coming_goods
    {
        public decimal id_merch { get; set; }
        public string brand { get; set; }
        public string name { get; set; }
        public decimal count_order { get; set; }
        public bool arrived { get; set; }
        public Nullable<System.DateTime> date_import { get; set; }
    }
}
