//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Send
    {
        public decimal id_invoice { get; set; }
        public decimal id_merch { get; set; }
        public decimal count { get; set; }
        public decimal price { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Merchandise Merchandise { get; set; }
    }
}
