//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_inv
    {
        public decimal id_user { get; set; }
        public decimal id_worktype { get; set; }
        public Nullable<System.DateTime> datatime { get; set; }
        public decimal id_invoice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Users Users { get; set; }
        public virtual Worktype Worktype { get; set; }
    }
}
