//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Inf
    {
        public decimal id_user { get; set; }
        public string phone { get; set; }
        public string adress { get; set; }
        public string mail { get; set; }
        public string notation { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
