//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_send_goods
    {
        public decimal Код_товара { get; set; }
        public decimal Кол_во_продано { get; set; }
        public decimal Себестоимость { get; set; }
        public decimal Наценка { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<System.DateTime> Дата_продажи { get; set; }
        public decimal Код_накладной { get; set; }
    }
}
