//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_merch
    {
        public decimal Код_товара { get; set; }
        public string Наименование { get; set; }
        public string Тип { get; set; }
        public string Описание { get; set; }
        public decimal Кол_во_заказано { get; set; }
        public decimal Кол_во_хранится { get; set; }
        public decimal Кол_во_продано { get; set; }
        public decimal Кол_во_зарезервированно { get; set; }
        public decimal C__партии { get; set; }
        public decimal Наценка { get; set; }
        public decimal Себестоимость { get; set; }
        public bool Брибытие { get; set; }
    }
}
